function run_single_seed_scenario(year, quarter, T, scenario, scale, seed, constraints, output_options)

    if nargin < 8
        output_options = struct('include_heavy_diagnostics', false);
    end

    output_options = resolve_output_options(output_options);

    fprintf('Starting single-seed simulation: %s (scale=1:%d, seed=%d, T=%d, CC=%d)\n', ...
        scenario, round(1/scale), seed, T, constraints);

    t_start = tic;
    cache = build_simulation_cache(year, quarter, scenario, scale, T);

    [nominal_gdp, real_gdp, nominal_gva, real_gva, ...
     nominal_household_consumption, real_household_consumption, ...
     nominal_government_consumption, real_government_consumption, ...
     nominal_capitalformation, real_capitalformation, ...
     nominal_fixed_capitalformation, real_fixed_capitalformation, ...
     nominal_fixed_capitalformation_dwellings, real_fixed_capitalformation_dwellings, ...
     nominal_exports, real_exports, nominal_imports, real_imports, ...
     operating_surplus, capital_consumption, compensation_employees, wages, ...
     taxes_production, nominal_sector_gva, real_sector_gva, ...
     sector_operating_surplus, sector_capital_consumption, ...
     nominal_output, real_output, nominal_sector_output, real_sector_output, ...
     government_debt, government_deficit, unemployment_rate, euribor, ...
     dyn_bilateral_trade_g, dyn_bilateral_trade_real_g, ...
     capital_stock_dynamics, capital_loss, sector_capital_loss, firms_damaged, ...
     loan_issuance, credit_constrained_pct, total_firms_demanding, ...
     credit_gap, credit_gap_to_gdp] = ...
        simulate_abm(year, quarter, seed, scenario, scale, T, constraints, cache, output_options);

    elapsed_seconds = toc(t_start);
    fprintf('Single-seed simulation completed in %.6f seconds\n', elapsed_seconds);

    results_dir = fullfile(getenv('HOME'), 'results');
    if ~exist(results_dir, 'dir')
        mkdir(results_dir);
    end

    output_file = fullfile(results_dir, sprintf('%s_%dQ%d_%d_seed%d_single.mat', ...
        scenario, year, quarter, round(1/scale), seed));

    save(output_file, ...
        'nominal_gdp', 'real_gdp', 'nominal_gva', 'real_gva', ...
        'nominal_household_consumption', 'real_household_consumption', ...
        'nominal_government_consumption', 'real_government_consumption', ...
        'nominal_capitalformation', 'real_capitalformation', ...
        'nominal_fixed_capitalformation', 'real_fixed_capitalformation', ...
        'nominal_fixed_capitalformation_dwellings', 'real_fixed_capitalformation_dwellings', ...
        'nominal_exports', 'real_exports', 'nominal_imports', 'real_imports', ...
        'operating_surplus', 'capital_consumption', 'compensation_employees', 'wages', ...
        'taxes_production', 'nominal_sector_gva', 'real_sector_gva', ...
        'sector_operating_surplus', 'sector_capital_consumption', ...
        'nominal_output', 'real_output', 'nominal_sector_output', 'real_sector_output', ...
        'government_debt', 'government_deficit', 'unemployment_rate', 'euribor', ...
        'dyn_bilateral_trade_g', 'dyn_bilateral_trade_real_g', ...
        'capital_stock_dynamics', 'capital_loss', 'sector_capital_loss', ...
        'firms_damaged', 'loan_issuance', 'credit_constrained_pct', ...
        'total_firms_demanding', 'credit_gap', 'credit_gap_to_gdp', ...
        'elapsed_seconds');

    fprintf('Results saved to: %s\n', output_file);
end
