% Helper function that runs a scenario and saves results on the cluster
% Called by run_batch via MATLAB batch() submission
function run_and_save_scenario(year, quarter, T, scenario, scale, seeds, constraints)

    fprintf('Starting simulation: %s (scale=1:%d, seeds=%d, T=%d, CC=%d)\n', ...
        scenario, round(1/scale), seeds, T, constraints);

    % Run simulation
    [nominal_gdp, real_gdp, nominal_gva, real_gva, ...
     nominal_household_consumption, real_household_consumption, ...
     nominal_government_consumption, real_government_consumption, ...
     nominal_capitalformation, real_capitalformation, ...
     nominal_fixed_capitalformation, real_fixed_capitalformation, ...
     nominal_fixed_capitalformation_dwellings, real_fixed_capitalformation_dwellings, ...
     nominal_exports, real_exports, nominal_imports, real_imports, ...
     operating_surplus, capital_consumption, compensation_employees, wages, ...
     taxes_production, nominal_sector_gva, real_sector_gva, ...
     sector_operating_surplus, sector_capital_consumption, ...
     nominal_output, real_output, nominal_sector_output, real_sector_output, ...
     government_debt, government_deficit, unemployment_rate, euribor, ...
     dyn_bilateral_trade_g, dyn_bilateral_trade_real_g, ...
     capital_stock_dynamics, capital_loss, sector_capital_loss, firms_damaged, ...
     loan_issuance, credit_constrained_pct, total_firms_demanding, ...
     credit_gap, credit_gap_to_gdp] = ...
        simulate_abm_mc(year, quarter, scenario, scale, seeds, T, constraints);

    fprintf('Simulation completed for %s\n', scenario);

    % Save to results/ in the user's home directory (cluster layout)
    results_dir = fullfile(getenv('HOME'), 'results');
    if ~exist(results_dir, 'dir')
        mkdir(results_dir);
    end
    output_file = fullfile(results_dir, sprintf('%s_%dQ%d_%d.mat', ...
        scenario, year, quarter, round(1/scale)));

    save(output_file, ...
        'nominal_gdp', 'real_gdp', 'nominal_gva', 'real_gva', ...
        'nominal_household_consumption', 'real_household_consumption', ...
        'nominal_government_consumption', 'real_government_consumption', ...
        'nominal_capitalformation', 'real_capitalformation', ...
        'nominal_fixed_capitalformation', 'real_fixed_capitalformation', ...
        'nominal_fixed_capitalformation_dwellings', 'real_fixed_capitalformation_dwellings', ...
        'nominal_exports', 'real_exports', 'nominal_imports', 'real_imports', ...
        'operating_surplus', 'capital_consumption', 'compensation_employees', 'wages', ...
        'taxes_production', 'nominal_sector_gva', 'real_sector_gva', ...
        'sector_operating_surplus', 'sector_capital_consumption', ...
        'nominal_output', 'real_output', 'nominal_sector_output', 'real_sector_output', ...
        'government_debt', 'government_deficit', 'unemployment_rate', 'euribor', ...
        'dyn_bilateral_trade_g', 'dyn_bilateral_trade_real_g', ...
        'capital_stock_dynamics', 'capital_loss', 'sector_capital_loss', ...
        'firms_damaged', 'loan_issuance', 'credit_constrained_pct', ...
        'total_firms_demanding', 'credit_gap', 'credit_gap_to_gdp');

    fprintf('Results saved to: %s\n', output_file);
end
